# Generated by Django 4.1.2 on 2022-11-23 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_coursefeedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseteacher',
            old_name='courses',
            new_name='course',
        ),
    ]
