# Generated by Django 4.1.2 on 2022-12-16 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            fields=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='age'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            fields=models.ImageField(blank=True, null=True, upload_to='users', verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            fields=models.EmailField(blank=True, max_lenght=254, unique=True, verbose_name='email'),
        ),
    ]

